### ISSUE TITLE
Blockstore can't serve SVG images correctly over S3

### ISSUE THREAD

**Issue by bradenmacdonald** [edx/blockstore#63]
When one uploads an SVG image to a Blockstore server that's storing data on Amazon S3, Blockstore will serve the image from a URL like

```
https://our-blockstore-content.s3.amazonaws.com/ca9635e6-a43e-40df-be67-1764d4a6b311/snapshot_data/6bc0efe8f1d9722615ca1d7042b85d5af115ca6f?AWSAccessKeyId=...&Expires=1575574652
```

S3 in turn serves that response with `Content-Type: application/octet-stream`

Unfortunately, this means that one cannot use `<img src="blockstore data URL" />` because browsers will not render SVG images that aren't served with the correct `Content-Type` header.

Possible solutions include:
* Change the data file name so it includes the file extension
* Have Blockstore know/detect the file type, and then [include the `response-content-type` parameter in the S3 signed URL request](https://stackoverflow.com/a/36306039), so S3 will serve it with the correct `Content-Type` header.

**Comment by bradenmacdonald** [comment]
This seems to apply to PDFs too; instead of displaying them inline in the browser, they just get downloaded as a file with a hexadecimal name.

**Comment by arbrandes** [comment]
For the record, this doesn't only affect S3: when Blockstore itself serves static files (such as on a devstack), SVGs are not rendered either.

**Comment by bradenmacdonald** [comment]
@arbrandes  @jvdm Sharing some thoughts here:

> Making sure the file extension is not lost would solve all the problems we are facing, wouldn't it?

I don't think so, because as far as I understand, S3 will always serve `Content-Type: application/octet-stream` regardless of the file extension. You must specify the content type during upload, or change it later like you'd change any other metadata. The reason you may not have encountered this before is that most AWS upload clients will detect the `Content-Type` from the file extension during upload and set it appropriately. (I could be wrong about this, but that's my current understanding. Could be worth a test.)

If that's the case, then you still need to set the content type explicitly at some point, and including the file extension in the filename doesn't help (or hurt). Renaming all existing uploaded BLOBs on S3 wouldn't help, but updating their content-type metadata would.

Where it does help is with the `FileSystemStorage` option, as nginx does look at the file extension to auto-detect the content type.

So I suspect that two different mechanisms may be needed, one for S3 and one for nginx ?

A few options:

Option 1
* Have Blockstore know/detect the file type, and then set the content-type metadata correctly during original upload to S3. (or don't set it on upload, but do include the response-content-type parameter in the S3 signed URL request, so S3 will serve it with the correct Content-Type header).
* For nginx/devstack, have blockstore generate a URL with `?content_type=foo/bar` and use an nginx rule to set the content-type header based on the query string. (Downside: requires adding a rule to nginx config)

Option 2
* Include file extension in the filename in the object store. Find a way to keep the name/hash unchanged for previously uploaded files. Make sure to handle case where two files are uploaded with different extensions but same content.
* Also set the content-type header explicitly when uploading to S3.

Potential for different mime types to be served from nginx vs. S3 with this approach, but likely not a big deal.

Option 3
* Proxy all files through blockstore. We'd talked about this previously for other reasons, but I think it's bad due to performance and taking up python threads.

**Comment by arbrandes** [comment]
@bradenmacdonald, thanks!  I like Option 1: it is the least invasive and carries the least risk.  Just thinking of having to predict and handle filename collisions gives me the jitters.  Only now realized the stored object name is an [actual digest of the file contents](https://github.com/edx/blockstore/blob/master/blockstore/apps/bundles/store.py#L320).  Thanks for clearing that up.

The nginx solution in Option 1 doesn't automatically fix the Blockstore devstack (I believe it serves via `django.views.static.serve()`), but with Blockstore moving into edx-platform this mechanism will have to be redesigned anyway.  I guess we can safely push back solving this particular facet of the problem.

@jvdm, thoughts?

**Comment by jvdm** [comment]
In essence, we need to ensure the file storage will serve the file with the correct content type. Setting the right content type sometimes happens at read-time (Django, Nginx) and sometimes it happens at write-time (S3). If we use file extensions, both mechanisms will be supported by the underlying storage by default. I know, [S3 needs some additional steps for that to happen](https://github.com/jschneier/django-storages/blob/770332b598712da27ecdba75c9e202ad6a1a8722/storages/backends/s3boto3.py#L488), but that doesn't matter because it occurs transparently.

With that out of the way, I need to understand the two concerns around Option 2, which I believe is about backward and forward compatibility:

1. Find a way to keep the name/hash unchanged for previously uploaded files.
2. Make sure to handle cases where two files are uploaded with different extensions but the same content.

Why can't we make the file extension part of the hash? Ideally, it should be, since content-type is supposed to be derived from its content. However, in my limited understanding of how Blockstore works, it feels like the only concern is mistakenly assuming a file does not exist when it does, dooming it to limbo (for example, when deleting it). Can we add additional logic to Blockstore to avoid that scenario, for example, by saving its "content-type" in the metadata JSON, and for now on, once it's is there, we "append" the extension to the file name and make it part of the hash, otherwise assume we are dealing with an "old named file"? That would make it backward and forward compatible.

I prefer solving this within Blockstore rather than dependency on the storage layer (e.g., specific configuration within Nginx, S3). Seems healthier. But in any case, you two have more context around the internals, so please, let me know why Option 1 seems more appealing.

**Comment by bradenmacdonald** [comment]
I actually thought that Option 2 is the most appealing, personally. I didn't have concerns about it, just notes.

> Why can't we make the file extension part of the hash?

You certainly can, as long as you don't break backward compatibility so there is some mechanism to use the "plain" hash for older files, and the hash with file extension for newer ones. The mechanism you suggest sounds good to me.

I only notice one very minor issue with this: Consider a JPEG file. You will often encounter file extensions like `.jpg`, `.JPG`, `.jpeg`, and `.JPEG`, and technically there are other valid ones like `.jif`, `.jfif`, etc. though they don't appear in the wild. If you incorporate the file extension into the hash, you will now sometimes store duplicate content under different hashes (blockstore's deduplication feature no longer works in 100% of cases). I don't think this is a big deal in practice; if it were happening with video files on blockstore or video chunk files on blockstore, though, it would be a problem.

> I prefer solving this within Blockstore rather than creating a dependency on the storage layer (e.g., specific configuration within Nginx, S3). Seems healthier this way.

I agree.

**Comment by arbrandes** [comment]
Alright, fine by me.  Option 2 it is, then.  @jvdm, would it be possible to get an implementation by Monday, or is this at risk of spilling over?

**Comment by bradenmacdonald** [comment]
Heads up @ormsbee as this is proposing a change to how blockstore file content hashes work and you may have thoughts.

**Comment by jvdm** [comment]
@bradenmacdonald:

> Heads up @ormsbee as this is proposing a change to how blockstore file content hashes work and you may have thoughts.

I think I've figured out a way to do this without altering how we hash the Snapshot files.

Considering that SnapshotStore is an append-only file storage, consistency errors or data leaks will not happen as long as we keep the file names that a particular version is using mapped correctly. That can be achieved by "bumping" the metadata JSON to support an optional `mime_type` attribute, and the naming schema changes based on this `mime_type` in the Snapshot store.

The benefit of this is, for files we cannot detect the MIME type, we can use the old naming schema to serve it with a default MIME-type header by the data plane -- the correct behavior. Another benefit is that old versions will continue to work since their metadata does not have a new field, leading to old-style naming.

Now to follow up on @bradenmacdonald remark:

> Make sure to handle case where two files are uploaded with different extensions but same content

They will be considered two different files from the Blockstore perspective. Is that a problem? Right now, I would say "No". I mean, it seems that the Blockstore design is to hold files as they were objects, but unless Blockstore aims towards adding an actual "object storage layer" where blobs are linked to names in some way in the data plane, I don't think we can have the same blob coexist with two names.

Anyway, [here's a preliminary PR with a potential fix](https://github.com/edx/blockstore/pull/118). It is still pending some UTs and ITs before I can remove the draft flag, but I think we can use it as a baseline for this discussion.

**Comment by bradenmacdonald** [comment]
@jvdm That approach seems good to me, yep. If you need a reviewer I can take a look later this week.

**Comment by jvdm** [comment]
@bradenmacdonald Thank you! Yes, please, grab this as a reviewer.
